server:
  port: 9000
  servlet:
    context-path: /workflow
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/activiti6?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&nullCatalogMeansCurrent=true
  activiti:
    check-process-definitions: false
    db-history-used: true
    history-level: full

